title: Investigating COVID-19 Virus Trends 
author: Eli Kliejunas
email: elidjunas@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  This project analyses data provided by Kaggle on responses to the COVID-19 pandemic worldwide. 

# social links
github_username:  elidjunas # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
